import {
  Menu,
  User,
  Search,
  SearchX,
  Plus,
  Minus,
  Trash2,
  ShoppingCart,
  CheckCircle,
  BadgeDollarSign,
  BookOpen,
  QrCode,
  LayoutDashboard,
  Package,
  FileText,
  Receipt,
  TrendingUp,
  Wallet,
  History,
  AlertCircle,
  AlertTriangle,
  Lightbulb,
  UserPlus,
  X,
  Save,
  Calendar,
  ArrowUpDown,
  ChevronRight,
  PackageX,
  ChartNoAxesColumnIncreasing,
  LogOut,
  Store,
  Edit,
  MoreVertical,
  Camera,
  Settings,
  Printer,
  MessageCircle,
  Bluetooth,
  Star,
  ScanBarcode,
  ShoppingBag,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  menu: Menu,
  account_circle: User,
  search: Search,
  search_off: SearchX,
  add: Plus,
  remove: Minus,
  delete: Trash2,
  shopping_cart: ShoppingCart,
  check_circle: CheckCircle,
  payments: BadgeDollarSign,
  menu_book: BookOpen,
  qr_code_2: QrCode,
  qr_code_scanner: ScanBarcode,
  scan_barcode: ScanBarcode,
  dashboard: LayoutDashboard,
  inventory_2: Package,
  package: Package,
  assessment: FileText,
  point_of_sale: Receipt,
  receipt: Receipt,
  file_text: FileText,
  trending_up: TrendingUp,
  account_balance_wallet: Wallet,
  history_edu: History,
  error: AlertCircle,
  warning: AlertTriangle,
  lightbulb: Lightbulb,
  person_search: SearchX,
  person_add: UserPlus,
  close: X,
  save: Save,
  calendar_month: Calendar,
  filter_list: ArrowUpDown,
  chevron_right: ChevronRight,
  production_quantity_limits: PackageX,
  picture_as_pdf: FileText,
  logout: LogOut,
  store: Store,
  edit: Edit,
  more_vert: MoreVertical,
  camera_switch: Camera,
  settings: Settings,
  print: Printer,
  message_circle: MessageCircle,
  receipt_long: Receipt,
  bluetooth: Bluetooth,
  star: Star,
  star_border: Star,
  shopping_bag: ShoppingBag,
};

export function Icon({ name, className = "", size = 24, fill }: { name: string; className?: string; size?: number; fill?: string }) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) {
    console.warn(`Unknown icon: ${name}`);
    return <span className={className}>?</span>;
  }
  return <LucideIcon className={`inline-block ${className}`.trim()} size={size} {...(fill !== undefined ? { fill } : {})} />;
}
